development:
  dialect: mysql
  datasource: root:root@tcp(localhost:1444)/dev?charset=utf8&parseTime=true
  dir: resources/migrations/schema/migrations
  table: migrations_schema_playground
# container:
#   dialect: mysql
#   datasource: $SUPERUSER_DATABASE_URL
#   dir: migrations
#   table: migrations_schema_playground
