-- +migrate Up
ALTER TABLE users
    CHANGE COLUMN emil email VARCHAR(255) NOT NULL UNIQUE,
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- +migrate Down
ALTER TABLE users
    CHANGE COLUMN email emil VARCHAR(255) NOT NULL UNIQUE,
    MODIFY COLUMN created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
